# Generated by Django 5.2.5 on 2025-09-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0002_bloodrequest_expires_at_bloodrequest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationhistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='accepted', max_length=10),
        ),
    ]
