# Generated by Django 5.2.5 on 2025-08-13 11:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, default='profile_pictures/default.jpg', max_length=255, null=True),
        ),
    ]
