# Generated by Django 5.2.5 on 2025-09-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_blood_group_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('donor', 'Donor'), ('requester', 'Requester'), ('hospital', 'Hospital'), ('admin', 'Admin')], default='donor', max_length=20),
        ),
    ]
