# Generated by Django 5.2.5 on 2025-09-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available'), ('busy', 'Busy')], default='available', max_length=20),
        ),
    ]
